x=5
y=2
x="c"
rm(x)
history(x)
help.search(rnom)
rm(x)
x=5
x="c"
x=8
myframe<-data.frame(age=numeric(0),gender=character(0),weight=numeric(0))
myframe<-edit(myframe)
library(xlsx)
mtframe<-read.xlsx(mydata)
attach(myframe)
detach(myframe)
attach(myframe)
plot(age,weight)
abline(lm(weight-age))
title("My Title")
detail(myframe)
pdf(abc,pdf)
pdf("abc.pdf")
dev.off()
dose<-c(20,30,40,45,60)
drugA<-c(16,20,27,40,60)
drugB<-c(15,18,25,31,40)
plot(dose,drugA)
plot(dose,drugA,type="b")
plot(dose,drugA,type="b",lty=1)
plot(dose,drugA,type="b",lty=1,pch=23)
plot(dose,drugA,type="b",lty=1,pch=23,cex=2)
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2)
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red")
color()
colour()
col.lab="green"
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red",col.lab="green")
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="yellow")
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="yellow",cex.axis=2)
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="yellow",cex.axis=2,cex.lab=2)
plot(dose,drugA,type="b",lty=1,pch=23,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="yellow",cex.axis=2,cex.lab=2)
myframe<-data.frame(qualitative=numeric(2),quantitative=numeric(2))
myframe<-edit(myframe)
q()
myframe<-data.frame(age=numeric(0),gender=charater(0),weight=numeric(0))
myframe<-data.frame(age=numeric(0),gender=character(0),weight=numeric(0))
myframe<-edit(myframe)
plot(age,weight)
attach(myframe)
plot(age,weight)
abline(ln(weight-age))
title("MY TITLE")
dose<-c(20,30,40,45,60)
drugA<-c(16,20,27,40,60)
drugB<-c(12,15,18,13,19)
plot(dose,drugA)
plot(dose,drugA,type="b")
plot(dose,drugA,type="b",lby=1:6)
plot(dose,drugA,type="b",lby=1)
plot(dose,drugA,type="b",lby=1,pch=23)
plot(dose,drugA,type="b",lby=1,pch=25)
plot(dose,drugA,type="b",lby=1,pch=25,cex=2)
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=8)
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2)
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="yellow")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="yellow")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="yellow",bg="pink")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="yellow",bg="pink",cex.axis="green")
q()
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="black")
plot(dose,drugA,type="b",lby=1,pch=25,cex=2,lwd=2,col.axis="red",col.lab="green",col.main="blue",fg="black",bg="pink")
q()
View(myframe)
View(myframe)
a=10
print(a)
b="hi"
print(b)
c=10.65
print(c)
a=10
b=20
c=a+b
print(c)
print(paste("addition=",c))
cat("Addition",c)
a=readline()
a=as.integer(readline())
b=as.integer(readline())
c=a+b
print(c)
a=65
b=66
a=10
b=20
c=a+b
a=as.integer(readline())
b=as.integer(readline())
a=65
b=67
a=as.character(a)
b=as.character(b)
a=6
if(a>5){}
print(as.character(a))
if(a>5){}
a=6
if(a>5){}
if(a>5){print(as.character(a))}
if(a>5{ print(convertColor())})
source('~/.RData', encoding = 'UTF-8')
a=1
as.character(a)
b=2
as.character(b)
c="one"
as.character(c)
a="A"
if('A'==a){ print("vowel")}
esle if('B'==c){ print("conjuget")}
esle if('B'==c){ print("conjuget")}}
a="A"
if('A'==a)
a="A"
if("A"==a,e,i,o,u){print("vowel")}
a="A"
a=1
if(a==1){
print("one")
}else if(a==2){
print("two")
a=1
if(a==1){
print("One")
}
a=2
if(a==1){
print("One")
}else if(a==2){
print("Two")
}
a="e"
if(a=="e"){
print("Vowel")
}else if(a==2){
print("Two")
}
a=1
x<-switch(
a,
"one"
"two"
"three"
)
print(x)
a=1
x<-switch(
a,
"one",
"two",
"three"
)
print(x)
a=3
x<-switch(
a,
"one",
"two",
"three"
)
print(x)
a=5
x<-switch(
a,
"one",
"two",
"three"
)
print(x)
x<-40
x
print(x)
x=40
print(x)
y<-x*40
y
z=x-y
z
print(X)
print(x)
s=x%y
s=x%%y
s
vec=c(1,2,3,4,5)
print(c)
print(vec)
vec<-c(1,2,3,4,5)
print(vec)
x**2
# we use ** operator for squre
x^2
6+5-4*3+2/4
# for multiple qperator,R uses bodmas rule
2**-0.5
# for root
2^-0.5
2^-0.5
